# Generated by Django 2.2.5 on 2020-05-27 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_bookedday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookedDay',
        ),
    ]
